### ISSUE TITLE
[EasyBugsnag] Could we notify Symfony Messenger Transport exceptions?

### ISSUE THREAD

**Issue by natepage** [eonx-com/easy-monorepo#615]
This error has happened, could we notify bugsnag for it? How?

PHP Fatal error: Uncaught Exception: String could not be parsed as XML in /var/www/vendor/async-aws/sqs/src/Result/ReceiveMessageResult.php:33
--
  | 2021-07-01T08:32:13.717+10:00 | Stack trace:
  | 2021-07-01T08:32:13.717+10:00 | #0 /var/www/vendor/async-aws/sqs/src/Result/ReceiveMessageResult.php(33): SimpleXMLElement->__construct()
  | 2021-07-01T08:32:13.717+10:00 | #1 /var/www/vendor/async-aws/core/src/Result.php(133): AsyncAws\Sqs\Result\ReceiveMessageResult->populateResult()
  | 2021-07-01T08:32:13.717+10:00 | #2 /var/www/vendor/async-aws/sqs/src/Result/ReceiveMessageResult.php(26): AsyncAws\Core\Result->initialize()
  | 2021-07-01T08:32:13.717+10:00 | #3 /var/www/vendor/symfony/amazon-sqs-messenger/Transport/Connection.php(216): AsyncAws\Sqs\Result\ReceiveMessageResult->getMessages()
  | 2021-07-01T08:32:13.717+10:00 | #4 /var/www/vendor/symfony/amazon-sqs-messenger/Transport/Connection.php(343): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection->fetchMessage()
  | 2021-07-01T08:32:13.717+10:00 | #5 /var/www/vendor/symfony/amazon-sqs-messenger/Transport/Connection.php(78): Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection->reset()
  | 2021-07-01T08:32:13.717+10:00 | #6 [internal function]: Symfony\Component\Messenger\Bridge\AmazonSqs\Transport\Connection->__destruct()
  | 2021-07-01T08:32:13.717+10:00 | #7 in /var/www/vendor/async-aws/sqs/src/Result/ReceiveMessageResult.php on line 33

**Comment by natepage** [comment]
Done in #667
